import { describe, test, expect } from 'vitest';
import { renderLlmsTxt, classifyLlmsTxt, urlToTitle } from '../llmstxt.js';

describe('renderLlmsTxt', () => {
  test('renders site name as h1 and entries as list items', () => {
    const out = renderLlmsTxt('mysite', [
      { title: 'Home', mdUrl: '/index.md', description: 'Welcome', hasDynamicMetadata: false },
      { title: 'About', mdUrl: '/about.md', description: null, hasDynamicMetadata: false },
    ]);
    expect(out).toBe('# mysite\n\n- [Home](/index.md): Welcome\n- [About](/about.md)\n');
  });

  test('uses dynamic placeholder when hasDynamicMetadata is true', () => {
    const out = renderLlmsTxt('mysite', [
      { title: 'Product', mdUrl: '/product.md', description: null, hasDynamicMetadata: true },
    ]);
    expect(out).toContain('dynamic — see generateMetadata()');
  });

  test('dynamic placeholder takes precedence over null description', () => {
    const out = renderLlmsTxt('mysite', [
      { title: 'Blog', mdUrl: '/blog.md', description: 'Static', hasDynamicMetadata: true },
    ]);
    expect(out).toContain('dynamic — see generateMetadata()');
    expect(out).not.toContain('Static');
  });

  test('omits colon when no description and not dynamic', () => {
    const out = renderLlmsTxt('s', [
      { title: 'Bare', mdUrl: '/bare.md', description: null, hasDynamicMetadata: false },
    ]);
    expect(out).toBe('# s\n\n- [Bare](/bare.md)\n');
  });

  test('uses root-relative URLs', () => {
    const out = renderLlmsTxt('s', [
      { title: 'Page', mdUrl: '/nested/page.md', description: null, hasDynamicMetadata: false },
    ]);
    expect(out).toContain('(/nested/page.md)');
  });
});

describe('urlToTitle', () => {
  test('root path returns Home', () => {
    expect(urlToTitle('/')).toBe('Home');
  });

  test('single segment is capitalized', () => {
    expect(urlToTitle('/about')).toBe('About');
  });

  test('nested path uses last segment', () => {
    expect(urlToTitle('/blog/my-post')).toBe('My post');
  });

  test('hyphens become spaces', () => {
    expect(urlToTitle('/get-started')).toBe('Get started');
  });
});

describe('classifyLlmsTxt', () => {
  test('banner → telogen', () => {
    expect(classifyLlmsTxt('# site\n<!-- generated by telogen v0.1.5 -->\n\n- [Home](/index.md)\n'))
      .toBe('telogen');
  });

  test('v0.1.4 shape without banner → telogen-legacy', () => {
    expect(classifyLlmsTxt('# my-app\n\n- [Home](/index.md): Welcome\n- [About](/about.md)\n'))
      .toBe('telogen-legacy');
  });

  test('handcrafted prose → foreign', () => {
    expect(classifyLlmsTxt('# My docs\n\nSome prose an agent should read.\n')).toBe('foreign');
  });

  test('no H1 first → foreign', () => {
    expect(classifyLlmsTxt('welcome to my site\n')).toBe('foreign');
  });
});

describe('banner placement', () => {
  test('banner renders after H1, before entries', () => {
    const out = renderLlmsTxt('site', [
      { title: 'Home', mdUrl: '/index.md', description: null, hasDynamicMetadata: false },
    ], '<!-- generated by telogen v0.1.5 -->');
    const lines = out.split('\n');
    expect(lines[0]).toBe('# site');
    expect(lines[1]).toBe('<!-- generated by telogen v0.1.5 -->');
    expect(lines[3]).toContain('[Home](/index.md)');
  });

  test('no banner param → unchanged legacy shape', () => {
    const out = renderLlmsTxt('site', []);
    expect(out).toBe('# site\n\n');
  });
});

describe('banner position hardening', () => {
  test('banner quoted in the body does not classify as telogen', () => {
    const handcrafted =
      '# My docs\n\nThis site is not generated; telogen adds `<!-- generated by telogen v0.1.5 -->` after the H1.\n';
    expect(classifyLlmsTxt(handcrafted)).toBe('foreign');
  });
});
