import * as fs from 'fs/promises';
import * as path from 'path';
import { parse } from '@babel/parser';
import _traverse from '@babel/traverse';
// @babel/traverse is CommonJS; in ESM bundles the function is on .default
const traverse = ((_traverse as any).default ?? _traverse) as typeof _traverse;
import * as t from '@babel/types';
import fg from 'fast-glob';

export interface PropHint {
  type: 'prop';
  elementName: string;
  propName: string;
  line: number;
}

export interface LiteralHint {
  type: 'literal';
  parentElement: string;
  preview: string;
  line: number;
}

export type AnnotationHint = PropHint | LiteralHint;

export interface FileAnnotations {
  filePath: string;
  hints: AnnotationHint[];
}

const CONTENT_PROPS = new Set([
  'title', 'description', 'body', 'content',
  'text', 'label', 'heading', 'caption', 'summary',
]);

async function readTelogenIgnore(projectRoot: string): Promise<string[]> {
  try {
    const raw = await fs.readFile(path.join(projectRoot, '.telogenignore'), 'utf-8');
    return raw
      .split('\n')
      .map(l => l.trim())
      .filter(l => l && !l.startsWith('#'))
      .map(normalizeIgnorePattern);
  } catch {
    return [];
  }
}

// Bare paths like `lib` or `components/icons/` have no glob metachars and
// match nothing in fast-glob's ignore array. Normalize them to `dir/**`.
function normalizeIgnorePattern(pattern: string): string {
  if (/[*?[\]{]/.test(pattern)) return pattern;
  return pattern.replace(/\/$/, '') + '/**';
}

export async function scanForAnnotations(projectRoot: string): Promise<FileAnnotations[]> {
  const userIgnore = await readTelogenIgnore(projectRoot);

  const files = await fg('**/*.{tsx,ts,jsx,js}', {
    cwd: projectRoot,
    absolute: true,
    ignore: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/*.test.*',
      '**/*.spec.*',
      ...userIgnore,
    ],
  });

  const fileResults = await Promise.all(
    files.map(async (filePath): Promise<FileAnnotations | null> => {
      let src: string;
      try {
        src = await fs.readFile(filePath, 'utf-8');
      } catch {
        return null;
      }

      let ast: ReturnType<typeof parse>;
      try {
        ast = parse(src, {
          sourceType: 'module',
          plugins: ['typescript', 'jsx', 'decorators-legacy'],
          errorRecovery: true,
        });
      } catch {
        return null;
      }

      const hints: AnnotationHint[] = [];

      traverse(ast, {
        JSXOpeningElement(nodePath) {
          const elementName = getElementName(nodePath.node.name);
          for (const attr of nodePath.node.attributes) {
            if (!t.isJSXAttribute(attr)) continue;
            const propName = t.isJSXIdentifier(attr.name) ? attr.name.name : null;
            if (!propName || !CONTENT_PROPS.has(propName)) continue;
            if (!t.isStringLiteral(attr.value) || !attr.value.value.trim()) continue;
            hints.push({
              type: 'prop',
              elementName,
              propName,
              line: attr.loc?.start.line ?? 0,
            });
          }
        },

        JSXText(nodePath) {
          const text = nodePath.node.value.trim();
          if (text.length <= 20) return;
          const parentEl = nodePath.parentPath;
          if (!t.isJSXElement(parentEl?.node)) return;
          const parentElement = getElementName((parentEl.node as t.JSXElement).openingElement.name);
          hints.push({
            type: 'literal',
            parentElement,
            preview: text.slice(0, 60),
            line: nodePath.node.loc?.start.line ?? 0,
          });
        },
      });

      if (hints.length === 0) return null;
      return { filePath: path.relative(projectRoot, filePath), hints };
    })
  );

  return fileResults.filter((r): r is FileAnnotations => r !== null);
}

export function renderAnnotationGuide(files: FileAnnotations[]): string {
  const lines: string[] = [
    '# AI Content Annotation Guide',
    '',
    'Generated by [telogen](https://github.com/ggange/telogen). telogen reads your route',
    'files directly, so it can\'t see content that lives inside child components. This file',
    'is a map of that content — the strings and elements telogen found but currently can\'t',
    'reach — with the exact spot you\'d mark each one for extraction.',
    '',
    '## How it works',
    '',
    '`<AIContent>` is a React Fragment wrapper — **zero DOM elements, zero layout impact.**',
    'It marks content for telogen to include in per-route `.md` files. Once a location is',
    'annotated, re-running `npx telogen` picks up that content.',
    '',
    'The `<AIContent>` component ships with `@telogen/react` in telogen Phase 2 — it is not',
    'published yet, so the suggestions below are a preview of where annotation will go, not',
    'something to install today. Watch [github.com/ggange/telogen](https://github.com/ggange/telogen)',
    'for the release.',
    '',
    '> **Note:** this file is regenerated on every `npx telogen` run — edits are ephemeral.',
    '> To permanently exclude files, add glob patterns to `.telogenignore` in your project root',
    '> (one pattern per line, `#` for comments, standard glob syntax).',
    '',
    '---',
    '',
  ];

  if (files.length === 0) {
    lines.push('> No annotation candidates found.');
    return lines.join('\n') + '\n';
  }

  for (const file of files) {
    lines.push(`## ${file.filePath}`, '');
    for (const hint of file.hints) {
      if (hint.type === 'prop') {
        lines.push(
          `- Wrap prop \`${hint.propName}\` on \`<${hint.elementName}>\` (line ${hint.line}): ` +
          `\`<AIContent label="${hint.propName}">{${hint.propName}}</AIContent>\``
        );
      } else {
        const ellipsis = hint.preview.length === 60 ? '...' : '';
        lines.push(
          `- Wrap literal "${hint.preview}${ellipsis}" (line ${hint.line}): ` +
          `\`<AIContent>${hint.preview}${ellipsis}</AIContent>\``
        );
      }
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

function getElementName(name: t.JSXOpeningElement['name']): string {
  if (t.isJSXIdentifier(name)) return name.name;
  if (t.isJSXMemberExpression(name)) return getElementName(name.object);
  return '';
}
