import * as fs from 'fs/promises';
import * as path from 'path';
import { parseSource } from './parse.js';
import _traverse from '@babel/traverse';
// @babel/traverse is CommonJS; in ESM bundles the function is on .default
const traverse = ((_traverse as any).default ?? _traverse) as typeof _traverse;
import * as t from '@babel/types';
import fg from 'fast-glob';

export interface PropHint {
  type: 'prop';
  elementName: string;
  propName: string;
  line: number;
}

export interface LiteralHint {
  type: 'literal';
  parentElement: string;
  preview: string;
  line: number;
}

export type AnnotationHint = PropHint | LiteralHint;

export interface FileAnnotations {
  filePath: string;
  hints: AnnotationHint[];
}

const CONTENT_PROPS = new Set([
  'title', 'description', 'body', 'content',
  'text', 'label', 'heading', 'caption', 'summary',
]);

async function readTelogenIgnore(projectRoot: string): Promise<string[]> {
  try {
    const raw = await fs.readFile(path.join(projectRoot, '.telogenignore'), 'utf-8');
    return raw
      .split('\n')
      .map(l => l.trim())
      .filter(l => l && !l.startsWith('#'))
      .map(normalizeIgnorePattern);
  } catch {
    return [];
  }
}

// Bare paths like `lib` or `components/icons/` have no glob metachars and
// match nothing in fast-glob's ignore array. Normalize them to `dir/**`.
function normalizeIgnorePattern(pattern: string): string {
  if (/[*?[\]{]/.test(pattern)) return pattern;
  return pattern.replace(/\/$/, '') + '/**';
}

// Read/parse at most this many files at a time — an unbounded Promise.all
// over a monorepo-sized file list exhausts file descriptors and memory.
const SCAN_CONCURRENCY = 32;

// Skip files larger than this; generated bundles and vendored blobs dominate
// above it and parsing them stalls the scan.
const MAX_FILE_BYTES = 512 * 1024;

// Stop rendering guide entries past this size — a multi-MB guide is noise,
// not a map. Whole files are dropped (never partial file sections).
const MAX_GUIDE_BYTES = 256 * 1024;

export async function scanForAnnotations(projectRoot: string): Promise<FileAnnotations[]> {
  const userIgnore = await readTelogenIgnore(projectRoot);

  const files = await fg('**/*.{tsx,ts,jsx,js}', {
    cwd: projectRoot,
    absolute: true,
    ignore: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/build/**',
      '**/out/**',
      '**/coverage/**',
      '**/.turbo/**',
      '**/.vercel/**',
      '**/storybook-static/**',
      '**/*.test.*',
      '**/*.spec.*',
      ...userIgnore,
    ],
  });

  const fileResults: Array<FileAnnotations | null> = [];
  for (let i = 0; i < files.length; i += SCAN_CONCURRENCY) {
    const batch = files.slice(i, i + SCAN_CONCURRENCY);
    fileResults.push(...(await Promise.all(batch.map(scanFile(projectRoot)))));
  }

  return fileResults.filter((r): r is FileAnnotations => r !== null);
}

function scanFile(projectRoot: string) {
  return async (filePath: string): Promise<FileAnnotations | null> => {
      let src: string;
      try {
        const stat = await fs.stat(filePath);
        if (stat.size > MAX_FILE_BYTES) return null;
        src = await fs.readFile(filePath, 'utf-8');
      } catch {
        return null;
      }

      const ast = parseSource(src);
      if (!ast) return null;

      const hints: AnnotationHint[] = [];

      traverse(ast, {
        JSXOpeningElement(nodePath) {
          const elementName = getElementName(nodePath.node.name);
          for (const attr of nodePath.node.attributes) {
            if (!t.isJSXAttribute(attr)) continue;
            const propName = t.isJSXIdentifier(attr.name) ? attr.name.name : null;
            if (!propName || !CONTENT_PROPS.has(propName)) continue;
            if (!t.isStringLiteral(attr.value) || !attr.value.value.trim()) continue;
            hints.push({
              type: 'prop',
              elementName,
              propName,
              line: attr.loc?.start.line ?? 0,
            });
          }
        },

        JSXText(nodePath) {
          const text = nodePath.node.value.trim();
          if (text.length <= 20) return;
          const parentEl = nodePath.parentPath;
          if (!t.isJSXElement(parentEl?.node)) return;
          const parentElement = getElementName((parentEl.node as t.JSXElement).openingElement.name);
          hints.push({
            type: 'literal',
            parentElement,
            preview: text.slice(0, 60),
            line: nodePath.node.loc?.start.line ?? 0,
          });
        },
      });

      if (hints.length === 0) return null;
      return { filePath: path.relative(projectRoot, filePath), hints };
  };
}

export function renderAnnotationGuide(files: FileAnnotations[]): string {
  const lines: string[] = [
    '# AI Content Annotation Guide',
    '',
    'Generated by [telogen](https://github.com/ggange/telogen). telogen reads your route',
    'files directly, so it can\'t see content that lives inside child components. This file',
    'is a map of that content — the strings and elements telogen found but currently can\'t',
    'reach — with the exact spot you\'d mark each one for extraction.',
    '',
    '## How it works',
    '',
    '`<AIContent>` will be a React Fragment wrapper — **zero DOM elements, zero layout',
    'impact.** Once it ships, it will mark content for telogen to include in per-route',
    '`.md` files.',
    '',
    'The `<AIContent>` component (from `@telogen/react`) and the CLI-side support for',
    'reading it both ship together in telogen Phase 2 — neither exists yet, so the',
    'suggestions below are a preview of where annotation will go, not something to use',
    'today. Watch [github.com/ggange/telogen](https://github.com/ggange/telogen) for the',
    'release.',
    '',
    '> **Note:** this file is regenerated on every `npx telogen` run — edits are ephemeral.',
    '> To permanently exclude files, add glob patterns to `.telogenignore` in your project root',
    '> (one pattern per line, `#` for comments, standard glob syntax).',
    '',
    '---',
    '',
  ];

  if (files.length === 0) {
    lines.push('> No annotation candidates found.');
    return lines.join('\n') + '\n';
  }

  let bytes = lines.join('\n').length;
  let rendered = 0;

  for (const file of files) {
    if (bytes > MAX_GUIDE_BYTES) break;

    const fileLines: string[] = [`## ${file.filePath}`, ''];
    for (const hint of file.hints) {
      if (hint.type === 'prop') {
        fileLines.push(
          `- Wrap prop \`${hint.propName}\` on \`<${hint.elementName}>\` (line ${hint.line}): ` +
          `\`<AIContent label="${hint.propName}">{${hint.propName}}</AIContent>\``
        );
      } else {
        const ellipsis = hint.preview.length === 60 ? '...' : '';
        fileLines.push(
          `- Wrap literal "${hint.preview}${ellipsis}" (line ${hint.line}): ` +
          `\`<AIContent>${hint.preview}${ellipsis}</AIContent>\``
        );
      }
    }
    fileLines.push('');

    lines.push(...fileLines);
    bytes += fileLines.join('\n').length + 1;
    rendered++;
  }

  if (rendered < files.length) {
    lines.push(
      `> **Guide truncated:** showing ${rendered} of ${files.length} files with candidates. ` +
      'Add patterns to `.telogenignore` to narrow the scan.',
      ''
    );
  }

  return lines.join('\n').trimEnd() + '\n';
}

function getElementName(name: t.JSXOpeningElement['name']): string {
  if (t.isJSXIdentifier(name)) return name.name;
  if (t.isJSXMemberExpression(name)) return getElementName(name.object);
  return '';
}
