import * as path from 'path';
import * as fs from 'fs/promises';
import { realpathSync } from 'fs';
import { fileURLToPath } from 'url';
import { detectRoutes } from './router.js';
import { extractContent, type ExtractedContent } from './visitor.js';
import { renderLlmsTxt, classifyLlmsTxt, urlToTitle, type LlmsTxtEntry } from './llmstxt.js';
import { scanForAnnotations, renderAnnotationGuide } from './annotation-guide.js';
import { KnownError, UsageError } from './errors.js';
import { buildIssueUrl, stripAbsolutePaths } from './issue-url.js';

// Injected by tsup at build time; the typeof guard keeps unbundled runs
// (vitest imports the source directly) working.
declare const __VERSION__: string;
export const VERSION = typeof __VERSION__ !== 'undefined' ? __VERSION__ : '0.0.0-dev';

const BANNER = `<!-- generated by telogen v${VERSION} -->`;

export interface CliFlags {
  out: string;
  skipDynamic: boolean;
  skipComponents: string[];
  force: boolean;
  help: boolean;
}

const KNOWN_FLAGS = ['--out', '--skip-dynamic', '--skip-components', '--force', '--help'];

export function parseArgs(argv: string[]): CliFlags {
  const flags: CliFlags = {
    out: 'public',
    skipDynamic: false,
    skipComponents: [],
    force: false,
    help: false,
  };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--out') {
      if (!argv[i + 1] || argv[i + 1].startsWith('--')) {
        throw new UsageError('--out requires a directory argument (e.g. --out public)');
      }
      flags.out = argv[++i];
    }
    else if (argv[i] === '--skip-dynamic') flags.skipDynamic = true;
    else if (argv[i] === '--skip-components') {
      if (!argv[i + 1] || argv[i + 1].startsWith('--')) {
        throw new UsageError('--skip-components requires a comma-separated list (e.g. --skip-components NavBar,Sidebar)');
      }
      flags.skipComponents = argv[++i].split(',').map(s => s.trim()).filter(Boolean);
    }
    else if (argv[i] === '--force') flags.force = true;
    else if (argv[i] === '--help' || argv[i] === '-h') flags.help = true;
    else throw new UsageError(unknownArgMessage(argv[i]));
  }
  return flags;
}

function unknownArgMessage(arg: string): string {
  let msg = `unknown argument: ${arg}`;
  if (arg.startsWith('-')) {
    const suggestion = KNOWN_FLAGS
      .map(f => ({ f, d: levenshtein(arg, f) }))
      .sort((a, b) => a.d - b.d)[0];
    if (suggestion && suggestion.d <= 3) msg += ` — did you mean ${suggestion.f}?`;
  }
  return msg + ` (run telogen --help for usage)`;
}

function levenshtein(a: string, b: string): number {
  const dp = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 1; j <= b.length; j++) dp[0][j] = j;
  for (let i = 1; i <= a.length; i++) {
    for (let j = 1; j <= b.length; j++) {
      dp[i][j] = Math.min(
        dp[i - 1][j] + 1,
        dp[i][j - 1] + 1,
        dp[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1)
      );
    }
  }
  return dp[a.length][b.length];
}

interface RouteResult {
  route: { filePath: string; url: string };
  content: ExtractedContent | null;
  /** set when extraction crashed — a stub .md is written instead */
  error: string | null;
}

export async function run(projectRoot: string, argv: string[]): Promise<void> {
  const flags = parseArgs(argv);

  if (flags.help) {
    console.log(`
telogen — generate AI-readable markdown from your Next.js source

Usage: npx telogen [options]

Options:
  --out <dir>              Output directory (default: public)
  --skip-dynamic           Omit dynamic content placeholders
  --skip-components <list> Comma-separated JSX element names to exclude (e.g. NavBar,Sidebar)
  --force                  Overwrite an existing llms.txt that telogen didn't generate
  --help                   Show this help
`);
    return;
  }

  console.log(`telogen v${VERSION}`);

  const { routes, skipped, duplicates, router } = await detectRoutes(projectRoot);

  if (router === 'none') {
    throw new KnownError(
      'no Next.js project found (missing app/, pages/, src/app/, or src/pages/ directory)'
    );
  }

  for (const f of skipped) {
    console.warn(`telogen: skipped dynamic route: ${path.relative(projectRoot, f)}`);
  }
  for (const dup of duplicates) {
    console.warn(
      `telogen: duplicate URL ${dup.url} — ignoring ${path.relative(projectRoot, dup.filePath)} (first file wins)`
    );
  }

  if (routes.length === 0) {
    throw new KnownError('no static routes found — nothing to generate');
  }

  const outDir = path.resolve(projectRoot, flags.out);
  await fs.mkdir(outDir, { recursive: true });

  await guardExistingLlmsTxt(outDir, flags.force, path.relative(projectRoot, outDir));

  const skipSet = new Set(flags.skipComponents);

  // Extraction failures are isolated per route: one unparseable file must
  // never take down the whole run (this is the literal HN first-run path).
  const results: RouteResult[] = await Promise.all(
    routes.map(async (route): Promise<RouteResult> => {
      try {
        const content = await extractContent(route.filePath, skipSet.size > 0 ? skipSet : undefined);
        return { route, content, error: null };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.warn(
          `telogen: failed to extract ${path.relative(projectRoot, route.filePath)}: ${stripAbsolutePaths(message)}`
        );
        return { route, content: null, error: message };
      }
    })
  );

  // Write .md files
  const llmsTxtEntries: LlmsTxtEntry[] = [];
  const written: string[] = [];

  for (const { route, content, error } of results) {
    const mdFilename = route.url === '/' ? 'index.md' : `${route.url.slice(1)}.md`;
    const mdPath = path.join(outDir, mdFilename);
    await fs.mkdir(path.dirname(mdPath), { recursive: true });

    const md = error !== null || content === null
      ? `<!-- extraction failed — content available at runtime via ${route.url} -->\n`
      : renderMarkdown(content, route.url, flags.skipDynamic);
    await fs.writeFile(mdPath, md, 'utf-8');
    written.push(mdPath);

    llmsTxtEntries.push({
      title: content?.title ?? urlToTitle(route.url),
      mdUrl: `/${mdFilename}`,
      description: content?.description ?? null,
      hasDynamicMetadata: content?.hasDynamicMetadata ?? false,
    });
  }

  // Write llms.txt
  const llmsTxt = renderLlmsTxt(path.basename(projectRoot), llmsTxtEntries, BANNER);
  const llmsTxtPath = path.join(outDir, 'llms.txt');
  await fs.writeFile(llmsTxtPath, llmsTxt, 'utf-8');
  written.push(llmsTxtPath);

  for (const p of written) {
    console.log(`telogen: wrote ${path.relative(projectRoot, p)}`);
  }

  // Coverage summary: guides the "my page came out empty" moment toward the
  // annotation guide instead of a bug report.
  const unreachable = results.filter(r => r.error !== null).length;
  const mostlyEmpty = results.filter(r => r.error === null && r.content!.blocks.length === 0).length;
  const withContent = results.length - unreachable - mostlyEmpty;
  const parts = [`${withContent} with content`];
  if (mostlyEmpty > 0) parts.push(`${mostlyEmpty} mostly empty`);
  if (unreachable > 0) parts.push(`${unreachable} unreachable`);
  console.log(
    `telogen: ${results.length} route${results.length === 1 ? '' : 's'} → ${parts.join(', ')} — see ai-annotation-guide.md`
  );

  // Write ai-annotation-guide.md — never fatal: a pathological repo layout
  // must not kill the run after the main output already succeeded.
  try {
    const annotations = await scanForAnnotations(projectRoot);
    const guide = renderAnnotationGuide(annotations);
    await fs.writeFile(path.join(projectRoot, 'ai-annotation-guide.md'), guide, 'utf-8');
    console.log('telogen: wrote ai-annotation-guide.md');
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(`telogen: annotation guide skipped (scan failed: ${stripAbsolutePaths(message)})`);
  }

  // Aggregated per-route failures → one pre-filled issue URL at end of run.
  if (unreachable > 0) {
    const errors = results.filter(r => r.error !== null).map(r => r.error as string);
    console.error(
      `\ntelogen: ${unreachable} route${unreachable === 1 ? '' : 's'} failed to extract. ` +
        'This is likely a telogen bug — you can report it with one click:\n' +
        buildIssueUrl(VERSION, errors)
    );
  }
}

/**
 * Refuses to clobber an llms.txt telogen didn't generate (D16). Three cases:
 * ours (banner) → overwrite; v0.1.4 shape (no banner yet) → warn + proceed;
 * anything else → require --force.
 */
async function guardExistingLlmsTxt(outDir: string, force: boolean, displayDir: string): Promise<void> {
  if (force) return;
  let existing: string;
  try {
    existing = await fs.readFile(path.join(outDir, 'llms.txt'), 'utf-8');
  } catch {
    return;
  }
  const origin = classifyLlmsTxt(existing);
  if (origin === 'telogen-legacy') {
    console.warn(
      `telogen: overwriting ${displayDir}/llms.txt — it matches telogen output from an older version`
    );
  } else if (origin === 'foreign') {
    throw new KnownError(
      `${displayDir}/llms.txt already exists and does not look telogen-generated — ` +
        're-run with --force to overwrite it'
    );
  }
}

function renderMarkdown(
  content: ExtractedContent,
  url: string,
  skipDynamic: boolean
): string {
  const lines: string[] = [];

  // Banner sits after the H1 when there is one — parsers key on H1-first.
  if (content.title) lines.push(`# ${content.title}`, BANNER, '');
  else lines.push(BANNER, '');
  if (content.description) lines.push(content.description, '');

  if (content.isDynamic && !skipDynamic) {
    lines.push(`<!-- dynamic content — available at runtime via ${url} -->`);
  }

  for (const block of content.blocks) {
    if (block.type === 'heading' && block.level) {
      lines.push('#'.repeat(block.level) + ' ' + block.text, '');
    } else if (block.type === 'listitem') {
      lines.push('- ' + block.text);
    } else {
      lines.push(block.text, '');
    }
  }

  return lines.join('\n').trimEnd() + '\n';
}

// Auto-execute only when run as the main script.
// Resolve process.argv[1] through realpath first: when invoked via a bin
// symlink (how `npx` and global installs work) argv[1] is the symlink path
// while import.meta.url is the resolved target. Comparing them raw fails and
// the CLI silently does nothing, so resolve the symlink before comparing.
function isMainModule(): boolean {
  const entry = process.argv[1];
  if (!entry) return false;
  const here = fileURLToPath(import.meta.url);
  try {
    return realpathSync(entry) === here;
  } catch {
    return entry === here;
  }
}

if (isMainModule()) {
  run(process.cwd(), process.argv.slice(2)).catch((err) => {
    const message = err instanceof Error ? err.message : String(err);
    console.error('telogen:', stripAbsolutePaths(message));
    if (!(err instanceof KnownError)) {
      console.error(
        '\nThis looks like a telogen bug — you can report it with one click:\n' +
          buildIssueUrl(VERSION, [message])
      );
    }
    process.exit(1);
  });
}
