export interface LlmsTxtEntry {
  /** display title — falls back to urlToTitle(url) at call site */
  title: string;
  /** root-relative path to the generated .md file, e.g. /about.md */
  mdUrl: string;
  description: string | null;
  hasDynamicMetadata: boolean;
}

/**
 * Renders a valid llms.txt index.
 *
 * Format per llmstxt.org spec:
 *   # Site Name
 *
 *   - [Page Title](/page.md): description
 *
 * Links are root-relative (/about.md) — unambiguous regardless of CDN path
 * or how the agent resolved the llms.txt URL.
 *
 * Pages with generateMetadata() get "dynamic — see generateMetadata()" as
 * the description so agents know the omission is intentional, not a bug.
 */
export function renderLlmsTxt(siteName: string, entries: LlmsTxtEntry[], banner?: string): string {
  // Banner goes AFTER the H1 — llms.txt parsers key on an H1-first document.
  const lines: string[] = [`# ${siteName}`, ...(banner ? [banner] : []), ''];

  for (const entry of entries) {
    const desc = entry.hasDynamicMetadata
      ? 'dynamic — see generateMetadata()'
      : (entry.description ?? '');

    lines.push(
      `- [${entry.title}](${entry.mdUrl})${desc ? ': ' + desc : ''}`
    );
  }

  return lines.join('\n') + '\n';
}

export type LlmsTxtOrigin = 'telogen' | 'telogen-legacy' | 'foreign';

/**
 * Decides whether an existing llms.txt is safe to overwrite.
 * - 'telogen': carries our version banner (v0.1.5+)
 * - 'telogen-legacy': no banner, but matches exactly the shape v0.1.4
 *   generated (H1 first line, every other non-empty line a `- [x](/y.md)`
 *   entry) — overwrite with a warning so upgraders aren't blocked
 * - 'foreign': anything else is presumed handcrafted → require --force
 */
export function classifyLlmsTxt(content: string): LlmsTxtOrigin {
  if (content.includes('<!-- generated by telogen v')) return 'telogen';

  const lines = content.split('\n').filter(l => l.trim() !== '');
  if (lines.length === 0) return 'telogen-legacy';
  if (!lines[0].startsWith('# ')) return 'foreign';
  const entryPattern = /^- \[[^\]]*\]\([^)]*\.md\)/;
  for (const line of lines.slice(1)) {
    if (!entryPattern.test(line)) return 'foreign';
  }
  return 'telogen-legacy';
}

/** Derives a human-readable title from a URL path when no metadata is available. */
export function urlToTitle(url: string): string {
  if (url === '/') return 'Home';
  const last = url.split('/').filter(Boolean).pop() ?? 'Page';
  return last.charAt(0).toUpperCase() + last.slice(1).replace(/-/g, ' ');
}
